export const surpriseMePrompts = [
  "Design a futuristic cityscape with floating buildings and advanced transportation systems.",
  "Create an otherworldly creature with a combination of features from different animals",
  "Imagine a surreal underwater scene where marine life interacts with unexpected elements",
  "Explore the world through artistic visions created by artists inspired by ancient civilizations",
  "Recreate your childhood dream home in virtual reality using augmented reality technology.",
  "Envision a future where everyone is connected to each other via social media, but only some",
  "Generate a whimsical forest filled with enchanted trees, talking animals, and magical pathways.",
  "Craft an abstract artwork that expresses the emotions of joy and serenity.",
  "Design a steampunk-inspired flying machine that defies conventional engineering.",
  "Create a vibrant and dynamic pattern inspired by the energy of a bustling city.",
  "Imagine a mythical land hidden within the clouds, inhabited by mystical creatures.",
  "Craft an imaginative logo for a company that specializes in time-travel adventures.",
  "Design an intricate mandala using elements inspired by nature and geometry.",
  "Create a futuristic fashion concept that combines technology and sustainable materials.",
  "Generate a serene and tranquil beach scene with pastel-colored skies and gentle waves.",
  "Imagine a whimsical world where plants have faces and personalities of their own.",
  "Design a logo for a virtual reality gaming company that transports players to new dimensions.",
  "Create a digital replica of a popular culture icon or historical figure.",
  "Generate an abstract representation of the concept of time using bold colors and shapes.",
  "Craft an intricate and ornate pattern inspired by ancient civilizations and mythology.",
  "Create a futuristic car concept with innovative features and a sleek, aerodynamic design.",
  "Imagine a scene from a post-apocalyptic world where nature reclaims urban landscapes.",
  "Design a tattoo inspired by cosmic elements and the mysteries of the universe.",
  "Generate a visually stunning illustration of a mythical creature in flight.",
  "Create a digital collage using vintage photographs, modern elements, and unexpected juxtapositions.",
];
